project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    
    toc: true
    toc-depth: 5
    toc-expand: 2
    toc-title: Table of content
    
    citations-hover: true
    footnotes-hover: true

website:
  title: "OutbreakTools documentation"
  favicon: images/icon.png
  repo-url: https://github.com/epicentre-msf/test-obt-doc-website
  
  # Options
  page-navigation: true
  back-to-top-navigation: true

  
  # Navbar
  navbar:
    search: true
    logo: images/icon.png
    
    left:
     - text: About
       href: about.qmd
        
    right: 
      - text: Getting started
        menu: 
          - text: Download and prepare the tools
            href: getting_started/download.qmd
          
          - text: General workflow
            href: getting_started/workflow.qmd
          
          - text: Prepare a linelist setup
            href: getting_started/create_dic.qmd
          
          - text: Compile a linelist
            href: getting_started/compile.qmd
            
      
      - text: Setup file reference
        menu: 
          - text: Dictionary sheet
            href: reference/dictionary_sheet.qmd
            
          - text: Choices sheet
            href: reference/choices_sheet.qmd
          
          - text: Analyses sheet
            href: reference/analyses_sheet.qmd
          
          - text: Export sheet
            href: reference/exports_sheet.qmd
          
          - text: Translation sheet
            href: reference/translations_sheet.qmd
            
          - text: Ribbon tabs
            href: reference/ribbons.qmd
            

      - text: Tutoriels
        href: tutorial.qmd

      - text: How-to 
        menu:
          - text: Export subset of geo columns
            href: how_to/export_subset_geo.qmd

          - text: Create two data entry tables
            href: how_to/link_tables.qmd
            
          - text: Add a new linelist language
            href: how_to/add_language.qmd
            
          - text: Migrate a setup to an upgraded version
            href: how_to/migrate_setup.qmd            
            
          - text: Import a geobase in the linelist
            href: how_to/import_geobase.qmd
            
          - text: Show or hide variables in the linelist
            href: how_to/show_hide_variables.qmd
            
      - text: Cheatsheet
        menu:
          - text: Choosing variable controls
            href: cheatsheets/variable_control.qmd
            
          - text: Defining analyses
            href: cheatsheets/analyses.qmd
        
    tools:
      - icon: github
        text: Source Code
        href: https://github.com/epicentre-msf/outbreak-tools

  # sidebar:
  #   contents: auto

  # Footer
  page-footer:
    left: Developed by [![](images/epicentre.png){fig-alt="Epicentre logo" width=65px}](https://epicentre.msf.org/)
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

