---
title: "Import a geobase in the linelist"
---


## Download a geobase {#sec-geobase-download}

1.	In you internet browser, go to the [Geoapp](https://reports.msf.net/secure/app/outbreak-tools-geoapp). 

2. Use your account to connect. If you do not have one already, create one [here]( https://reports.msf.net/signup/) first then connect to the Geoapp.

3. Select one or more countries from the dropdown menu in the top left of the screen. The Admin 1 regions of each country will be rendered on the map.

4. Click on the regions you require geo data for. Once clicked, the region will turn red to indicate it has been selected. Alternatively, to select all regions currently rendered on the map, click the "Select all regions" button under the country dropdown menu. Once at least one region has been selected, buttons to inspect and download the data will appear below the country dropdown menu.

5. Clicking the "Download Geobase" button will download the data for the selected regions in the excel format that can be directly imported into an Outbreak Tools Linelist.


::: {.callout-note}
The geospatial administrative boundary data used to build the Geobase can also be downloaded in the format of your choice, compatible with GIS software (e.g. QGIS, ArcGIS) and the R statistical software by clicking on the "Download geo Data" button
:::
    

::: {.callout-tip}
You can select one or more countries. And you can select one or more regions of these countries. This allow you to select (cross-border) zones of interest and lighter geobases.
:::



## Import a geobase in a linelist {#sec-geobase-import}